name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Set up environment variables
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Install playwright
      run: npx playwright install

    - name: Install dependencies
      run: npm i

    - name: Start xvfb
      run: xvfb-run -s "-screen 0 1280x1024x24" npm run testOOP

    - name: Install Allure
      run: |
        npm install allure-commandline

    - name: Generate Allure report
      run: npm run report

    - name: Archive Allure report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report/

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
    
    - name: Print GitHub Pages URL
      run: |
        echo "GitHub Pages URL: ${{ steps.get_url.outputs.url }}"
    - name: Open GitHub Pages report
      run: open ${{ steps.get_url.outputs.url }}
      
  
