name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Set up environment variables
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Install xvfb
      run: sudo apt-get install xvfb

    - name: Install playwright
      run: npx playwright install

    - name: Install dependencies
      run: npm i

    - name: Start xvfb
      run: xvfb-run -s "-screen 0 1280x1024x24" npm run testOOP

    - name: Install Allure
      run: |
        npm install allure-commandline

    - name: Generate Allure report
      run: npm run report

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: target/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-report

      
  
